### ISSUE TITLE
ImportError: cannot import name ‘nvdla’ from ‘tvm.relay.op.contrib’

### ISSUE THREAD

**Issue by chayitw** [WuDan0399/Integrate-NVDLA-and-TVM#2]
Hi, WuDan,

Have a nice day, 

I try to run the example (python code) of “examples/run_LeNet_Relay.py”, and meet the issue:

File “examples/run_LeNet_Relay.py”, line 5, in from tvm.relay.op.contrib import nvdla ImportError: cannot import name ‘nvdla’ from ‘tvm.relay.op.contrib’ (/home/chayi/tvm/python/tvm/relay/op/contrib/init.py)

Then, i try to find ‘nvdla’ file in my TVM’s PYTHONPATH (e.g. ~/tvm/python/tvm/relay/op/contrib/) and see other versions of TVM (0.7/0.6/0.5),

BUT can’t see any file about ‘nvdla’ at the path (e.g. {TVM}/python/tvm/relay/op/contrib/) May i lose something, any suggestion? Appreciate your hand, thanks ^ ^

Thank U, -chayi

**Comment by shivmgg** [comment]
Please use the code files from https://github.com/shivmgg/tvm for NVDLA specific files.

**Comment by chayitw** [comment]
> Please use the code files from https://github.com/shivmgg/tvm for NVDLA specific files.

Hi shivmgg,
    Thank you.

    I just copy your "nvdla.py" and try to run at my TVM (v0.8), but stuck at a error:

  **Check failed: pf == false: Failed to find the codegen tool for relay.ext.nvdla**

   I am not familiar with TVM's customized "codegen", i think that i should build the "relay.ext.nvdla" at next step.
   I am the beginner of TVM, any suggestion is appreciated, thank U ^ ^

br,
chayi

The detail message is as below:

(py3.7) chayi@ailab03:~/workspace/tvm/tvm-main$ python examples/run_LeNet_Relay1.py
local_pyfunc= <function legalize_conv2d at 0x7f75f9a03440>
local_pyfunc= <function legalize_conv2d at 0x7f75f9a03440>
local_pyfunc= <function legalize_dense at 0x7f75f99f05f0>
local_pyfunc= <function legalize_dense at 0x7f75f99f05f0>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function dense_strategy_cpu at 0x7f7603d4d950>
local_pyfunc= <function wrap_compute_dense.<locals>._compute_dense at 0x7f75f8b99b00>
local_pyfunc= <function wrap_compute_dense.<locals>._compute_dense at 0x7f75f8b8e560>
Cannot find config for target=llvm -keys=cpu -link-params=0, workload=('dense_pack.x86', ('TENSOR', (1, 500), 'int8'), ('TENSOR', (10, 500), 'int8'), None, 'int8'). A fallback configuration is used, which may bring great performance regression.
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f9a03d40>
local_pyfunc= <function wrap_topi_schedule.<locals>.wrapper at 0x7f75f8b8e200>
local_pyfunc= <function lower at 0x7f75fa73c050>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function dense_strategy_cpu at 0x7f7603d4d950>
local_pyfunc= <function wrap_compute_dense.<locals>._compute_dense at 0x7f75f8b99440>
local_pyfunc= <function wrap_compute_dense.<locals>._compute_dense at 0x7f75f8b8e8c0>
Cannot find config for target=llvm -keys=cpu -link-params=0, workload=('dense_pack.x86', ('TENSOR', (1, 800), 'int8'), ('TENSOR', (500, 800), 'int8'), None, 'int8'). A fallback configuration is used, which may bring great performance regression.
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f9a03d40>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f99ece60>
local_pyfunc= <function wrap_topi_schedule.<locals>.wrapper at 0x7f75f8b8e290>
local_pyfunc= <function lower at 0x7f75fa73c050>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f99a6b00>
local_pyfunc= <function schedule_injective_cpu at 0x7f7603d47cb0>
local_pyfunc= <function lower at 0x7f75fa73c050>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f9a08d40>
local_pyfunc= <function schedule_pool_cpu at 0x7f7603d47e60>
local_pyfunc= <function lower at 0x7f75fa73c050>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function conv2d_strategy_cpu at 0x7f7603d4d560>
local_pyfunc= <function wrap_compute_conv2d.<locals>._compute_conv2d at 0x7f75f8b99290>
Cannot find config for target=llvm -keys=cpu -link-params=0, workload=('conv2d_NCHWc.x86', ('TENSOR', (1, 20, 12, 12), 'int8'), ('TENSOR', (50, 20, 5, 5), 'int8'), (1, 1), (0, 0, 0, 0), (1, 1), 'NCHW', 'NCHW', 'int8'). A fallback configuration is used, which may bring great performance regression.
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f9a03d40>
local_pyfunc= <function wrap_topi_schedule.<locals>.wrapper at 0x7f75f8b99d40>
local_pyfunc= <function lower at 0x7f75fa73c050>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f9a08d40>
local_pyfunc= <function schedule_pool_cpu at 0x7f7603d47e60>
local_pyfunc= <function lower at 0x7f75fa73c050>
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function conv2d_strategy_cpu at 0x7f7603d4d560>
local_pyfunc= <function wrap_compute_conv2d.<locals>._compute_conv2d at 0x7f75f8b9d3b0>
Cannot find config for target=llvm -keys=cpu -link-params=0, workload=('conv2d_NCHWc.x86', ('TENSOR', (1, 1, 28, 28), 'int8'), ('TENSOR', (20, 1, 5, 5), 'int8'), (1, 1), (0, 0, 0, 0), (1, 1), 'NCHW', 'NCHW', 'int8'). A fallback configuration is used, which may bring great performance regression.
local_pyfunc= <function lower_call at 0x7f75fa73d0e0>
local_pyfunc= <function _wrap_default_fstrategy.<locals>._fstrategy at 0x7f75f9a03d40>
local_pyfunc= <function wrap_topi_schedule.<locals>.wrapper at 0x7f75f8b9d440>
local_pyfunc= <function lower at 0x7f75fa73c050>
[[118, 40, 114, 5, -96, 63, -69, 110, -101, 107]]
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911bdd0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f910d4d0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911b9e0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911bdd0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f910d4d0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911b9e0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f910d3b0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911bf80>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f910d4d0>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911be60>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f911bf80>
local_pyfunc= <function _register_external_op_helper.<locals>._func_wrapper at 0x7f75f910d4d0>
Traceback (most recent call last):
  File "examples/run_LeNet_Relay1.py", line 164, in <module>
    lib = relay.build(module, target=target, params=params)
  File "/home/chayi/tvm/python/tvm/relay/build_module.py", line 283, in build
    graph_json, runtime_mod, params = bld_mod.build(ir_mod, target, target_host, params)
  File "/home/chayi/tvm/python/tvm/relay/build_module.py", line 132, in build
    self._build(mod, target, target_host)
  File "/home/chayi/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (6) /home/chayi/tvm/build/libtvm.so(TVMFuncCall+0x5b) [0x7f75ff94cd3b]
  [bt] (5) /home/chayi/tvm/build/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x3a0) [0x7f75ff774dd0]
  [bt] (4) /home/chayi/tvm/build/libtvm.so(tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::IRModule, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tvm::runtime::NDArray> > > const&)+0x48f) [0x7f75ff77240f]
  [bt] (3) /home/chayi/tvm/build/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::backend::GraphRuntimeCodegenModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x87) [0x7f75ff7b43e7]
  [bt] (2) /home/chayi/tvm/build/libtvm.so(tvm::relay::backend::GraphRuntimeCodegen::Codegen(tvm::relay::Function)+0x1725) [0x7f75ff7b3655]
  [bt] (1) /home/chayi/tvm/build/libtvm.so(tvm::relay::CompileEngineImpl::LowerExternalFunctions()+0xdf9) [0x7f75ff785ff9]
  [bt] (0) /home/chayi/tvm/build/libtvm.so(+0x1891b12) [0x7f75ff775b12]
  File "/home/willy/tvm/src/relay/backend/compile_engine.cc", line 663
TVMError:
---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: pf == false: Failed to find the codegen tool for relay.ext.nvdla

**Comment by shivmgg** [comment]
Please go through this doc: https://tvm.apache.org/docs/dev/relay_bring_your_own_codegen.html for a better understanding of TVM and codegen. 

You need to clone the TVM repo or make sure you copy all the changes in your repository to run our code.

**Comment by chayitw** [comment]
Hi Shivmgg,
   Thank You. Good Suggestion.
   And i use your TVM's branch source code to install and solve this issue.
   
   In my case, to solve this issue is to:
   **Install TVM from source using modified GitHub source code**.
   ( git clone --recursive https://github.com/shivmgg/tvm )

thanks,
--chayi
